name: torchtyping CI

on:
  pull_request:
    branches:
    - master

jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Format with black
        run: |
          python -m black --check torchtyping/

  test_suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e .
    - name: Test with pytest
      run: |
        python -m pytest test/
